version: '2.3'

services:

  salgan_pytorch:
    image: salgan_pytorch
    container_name: salgan_pytorch
    working_dir: /home
    build: .
    volumes:
      - ../src:/home/code
      - /home/enric/Downloads/juanjo/DATASETS/DHF1K:/home/dataset
      - /home/enric/Downloads/juanjo/TRAINED_MODELS/:/home/code/trained_models

    ports:
      - 6006:6006
      - 6007:6007
      - 8888:8888
    runtime: nvidia
