version: '2.3'

services:

  salgan_pytorch:
    image: salgan_pytorch
    container_name: salgan_pytorch
    working_dir: /home
    build: .
    volumes:
      - ../src:/home/code
      - /media/eHD/juanjo/DATASETS/SALICON:/home/dataset
      - /media/eHD/juanjo/TRAINED_MODELS/:/home/code/trained_models
      - /media/eHD/juanjo/SALIENCY_MAPS/:/home/saliency_maps
    environment:
      - PYTHONPATH=/home/code
    ports:
      - 6006:6006
      - 6007:6007
      - 8888:8888
    runtime: nvidia
